# -*- coding: utf-8 -*-
"""Helmet_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TpdiDlTGlY16wg0OyWhzzBX9HxricZxu

# Import Packages
"""

!pip install roboflow ultralytics

"""# Import Library"""

from ultralytics import YOLO
from roboflow import Roboflow
from google.colab import drive
import os

"""# Connect to Drive (i.e Here we store Our Model)"""

# Mount Google Drive
drive.mount('/content/drive')

# Paths
drive_path = "/content/drive/MyDrive/Helmet_Detection"
os.makedirs(drive_path, exist_ok=True)

"""# Import Dataset (From Roboflow)"""

# 1. Authenticate with your API key
rf = Roboflow(api_key="API Key")   # Replace with your API key

workspace_name = "smarthsrp"
project_name = "helmet-and-non-helmet-detection-03zb2"
version_number = 2  # the version you want to use

# Get the specific project and version
project = rf.workspace(workspace_name).project(project_name)
dataset = project.version(version_number).download("yolov8")  # download in YOLOv8 format use same format in yolov11

print("Dataset downloaded to:", dataset.location)

"""# Before Running below Line Check and Change the data.ymal path ⚓

test: /content/Helmet-and-Non-Helmet-Detection--2/test/images

train: /content/Helmet-and-Non-Helmet-Detection--2/train/images

val: /content/Helmet-and-Non-Helmet-Detection--2/valid/images
"""

# 4️⃣ Set paths
dataset_path = "/content/Helmet-and-Non-Helmet-Detection--2"
data_yaml = os.path.join(dataset_path, "data.yaml")
project_folder = "/content/plate_recognition_project"
run_name = "yolov10_plate"

print("Train images:", len(os.listdir(os.path.join(dataset_path, "train/images"))))
print("Validation images:", len(os.listdir(os.path.join(dataset_path, "valid/images"))))
print("Test images:", len(os.listdir(os.path.join(dataset_path, "test/images"))))

"""# Load Model"""

model = YOLO("yolo11s") # Path of the the last.pt or the  last epoch checkpoint i.e epoch50

model=YOLO('/content/drive/MyDrive/Helmet_Detection/Helmet_Detection_1/weights/last.pt')

"""# Train Model"""

model.train(
    data=data_yaml,
    epochs=100,
    imgsz=640,
    batch=16,
    # --- Augmentations
    hsv_h=0.012,
    hsv_s=0.5,
    hsv_v=0.3,
    degrees=4.0,
    translate=0.1,
    scale=0.6,
    shear=1.0,
    perspective=0.0004,
    flipud=0.0,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.12,
    copy_paste=0.05,
    # --- Training Config ---
    name="Helmet_Detection_1",
    project=drive_path,
    exist_ok=True,
    save_period=5,
    patience=10,
    resume=True
)

"""# Evalution On Test Data"""

model=YOLO("/content/drive/MyDrive/Helmet_Detection/Helmet_Detection_1/weights/best.pt")
model.val(data=data_yaml, batch=16, imgsz=640)

"""# **Metrics Summary**

---



## **Overall:**


  | Metric                      | All classes | Helmet | No-Helmet |
  | --------------------------- | ----------- | ------ | --------- |
  | **Precision (P)**           | 0.922       | 0.929  | 0.915     |
  | **Recall (R)**              | 0.846       | 0.847  | 0.846     |
  | **mAP@0.5 (mAP50)**         | 0.916       | 0.917  | 0.915     |
  | **mAP@0.5:0.95 (mAP50-95)** | 0.645       | 0.674  | 0.616     |



## **Strengths:**

High precision means the model rarely predicts false helmets.

mAP50 is excellent → good for typical detection use.

## **⚠ Weaknesses:**

Recall can improve → the model is missing some helmets/no-helmets.

mAP50-95 is moderate → performance drops under stricter overlap thresholds, meaning box localization could be improved.

# Single Infrence
"""

from ultralytics import YOLO

model = YOLO("Plate_Baseline.pt")
results=model.predict(source="path/to/image.jpg", save=True, conf=0.5)
results[0].show()

